# Generated by Django 3.2.6 on 2021-09-14 19:57

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=timezone.now() + datetime.timedelta(days=7), verbose_name='ending date'),
            preserve_default=False,
        ),
    ]
