# Generated by Django 3.2.6 on 2021-10-16 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 7, 19, 0, 803883, tzinfo=utc), verbose_name='date end'),
        ),
    ]
