# Generated by Django 3.2.6 on 2021-10-25 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 6, 25, 37, 483475, tzinfo=utc), verbose_name='date end'),
        ),
    ]
